### ISSUE TITLE
从加载和依赖的原理谈谈javascript性能优化

### ISSUE THREAD

**Issue by LDingLDing** [hdulp/read-and-share#2]
我们都知道script要放到body最后，这其中如何让js加载顺序的合理和不阻塞仍然是值得不断探究的问题。

[JavaScript 的性能优化：加载和执行 ](http://www.ibm.com/developerworks/cn/web/1308_caiys_jsload/index.html)
文章底部也有一些很好的链接。

**Comment by ahbing** [comment]
## 读了一下文章，做了一下笔记

### 要点
- script 的加载是请求到 js 代码立即执行，这会阻塞 js 的其他脚本下载

- 先进浏览器允许并行下载 js 文件， 但会阻塞其他资源下载比如样式，图片。页面也仍需要等待所有的 js 代码下载并执行完成才继续。

- 将脚本通常放在底部是因为，先去加载 html css 的资源，给用户的感觉就是不会有长时间的空白。

### 如何改进：
-  ﻿减少 js 脚本文件数量，下载单个 100Kb 的文件将比下载 5 个 20Kb 的文件更快。但如果 js 文件，过于庞大，会锁死浏览器。

- 添加 defer 属性，添加 defer 属性的脚本，不会修改 dom， 因此可以安全的延迟执行。

- ﻿添加 async 属性能够异步加载脚本，下载顺序不一定，且下载完成即刻执行， 所有使用该属性应该的 js 脚本， 不应该与其他脚本有依赖关系。

- 动态创建 script 标签，当设置 src 属性值的时候， 会执行 http 请求。﻿

- ﻿监听 onload 事件，在事件回调里面加载请求 js 资源。

    ﻿
